// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';

export function CreateNewGame(arg1:string,arg2:string):Promise<string>;

export function GetAvailableSaves():Promise<Array<data.SaveMeta>>;

export function LoadGameData(arg1:string):Promise<Record<string, string>>;

export function QuitGame():Promise<void>;

export function SetDisplayMode(arg1:string):Promise<void>;

export function SetResolution(arg1:number,arg2:number):Promise<void>;
