// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewGame(arg1, arg2) {
  return window['go']['main']['App']['CreateNewGame'](arg1, arg2);
}

export function GetAvailableSaves() {
  return window['go']['main']['App']['GetAvailableSaves']();
}

export function LoadGameData(arg1) {
  return window['go']['main']['App']['LoadGameData'](arg1);
}

export function QuitGame() {
  return window['go']['main']['App']['QuitGame']();
}

export function SetDisplayMode(arg1) {
  return window['go']['main']['App']['SetDisplayMode'](arg1);
}

export function SetResolution(arg1, arg2) {
  return window['go']['main']['App']['SetResolution'](arg1, arg2);
}
